version: "3.9"
services:
 phala-node:
  image: ${NODE_IMAGE}
  container_name: phala-node
  ports:
   - "9933:9933"
   - "9944:9944"
   - "30333:30333"
  environment:
   - NODE_NAME=${NODE_NAME}
     volumes:
   - "$HOME/phala-node-data:/root/data"

 phala-pruntime:
  image: ${PRUNTIME_IMAGE}
  container_name: phala-pruntime
  ports:
   - "8000:8000"
  volumes:
   - "$HOME/phala-pruntime-data:/root/data"
  depends_on:
   - phala-node
  devices:${SGXDRIVE}

 phala-phost:
  image: ${PHOST_IMAGE}
  container_name: phala-phost
  depends_on:
   - phala-node
   - phala-pruntime
  restart: always
  entrypoint: [
      "/root/phost",
      "--dev",
      "--mnemonic=${MNEMONIC}",
      "--substrate-ws-endpoint=ws://phala-node:9944",
      "--pruntime-endpoint=ws://phala-pruntime:8000",
      "--operator ${OPERATOR}"
    ]

  