version: "3"
services:
 phala-node:
   image: ${NODE_IMAGE}
   container_name: phala-node
   hostname: phala-node
   ports:
    - "9933:9933"
    - "9934:9934"
    - "9944:9944"
    - "9945:9945"
    - "30333:30333"
    - "30334:30334"
   environment:
    - NODE_NAME=${NODE_NAME}
    - NODE_ROLE=MINER
   volumes:
    - ${NODE_VOLUMES}
